"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const V = require("../v11-core.js");

let passed = 0;
function test(name, fn) { try { fn(); passed++; console.log(`✓ ${name}`); } catch (error) { console.error(`✗ ${name}\n  ${error.stack}`); process.exitCode=1; } }
function storage(initial={}) { const data=new Map(Object.entries(initial)); return { getItem:key=>data.get(key)??null, setItem:(key,value)=>data.set(key,String(value)), removeItem:key=>data.delete(key), data }; }

const mangaOnly = V.createStandaloneWork("manga", { id:"manga-1", title:"只有漫畫的作品", aliases:["Manga Only"], author:"作者甲", publisher:"出版社甲", status:"releasing", totalChapters:null });

test("1. 只有漫畫的作品可建立", () => { assert.equal(mangaOnly.mediaEntries.length,1); assert.equal(mangaOnly.mediaEntries[0].mediaType,"manga"); });
test("2. 沒有動畫時不報錯", () => { assert.equal(mangaOnly.mediaEntries.some(entry=>entry.mediaType==="anime"),false); assert.doesNotThrow(()=>V.normalizeWork(mangaOnly)); });
test("3. 只有漫畫時介面預設開漫畫分頁", () => { const source=fs.readFileSync(path.resolve(__dirname,"..","cross-media.js"),"utf8"); assert.match(source,/work\.mediaEntries\.length===1&&work\.mediaEntries\[0\]\.mediaType==="manga"\?work\.mediaEntries\[0\]/); assert.match(source,/此作品目前沒有動畫資料/); assert.match(source,/偵測是否宣布動畫化/); });
test("4. 舊 111 部動漫遷移不遺失且不重複", () => { const legacy=Array.from({length:111},(_,i)=>({id:i+1,title:`動畫 ${i+1}`,watched:i%12,currentEpisode:i%12,rating:8,note:"筆記",customPlatform:"動畫瘋",aliases:[`別名 ${i+1}`],relations:[{relationType:"SEQUEL"}],themeSongs:{openings:[],endings:[]}})); const first=V.migrateWorks(legacy,[]),second=V.migrateWorks(legacy,first); assert.equal(first.length,111);assert.equal(second.length,111);assert.equal(second.flatMap(w=>w.mediaEntries).length,111);const item=second[20].mediaEntries[0];for(const key of ["id","watched","currentEpisode","rating","note","customPlatform","relations","themeSongs"])assert.deepEqual(item[key],legacy[20][key]); });
test("5. 動畫 relations 可偵測原作漫畫", () => { const candidates=V.detectMangaCandidates({title:"動畫版",relations:[{relationType:"SOURCE",node:{id:99,type:"MANGA",format:"MANGA",title:{native:"原作漫畫"},status:"RELEASING",chapters:150,volumes:18}}]}); assert.equal(candidates.length,1);assert.equal(candidates[0].title,"原作漫畫");assert.equal(candidates[0].relationConfidence,100); });
test("6. 多個漫畫候選不會全部自動加入", () => { const work=V.createStandaloneWork("anime",{id:"a1",title:"動畫"});const relations=[{relationType:"SOURCE",node:{id:1,type:"MANGA",format:"MANGA",title:{native:"原作"}}},{relationType:"ALTERNATIVE",node:{id:2,type:"MANGA",format:"MANGA",title:{native:"外傳"}}}];const candidates=V.detectMangaCandidates({relations});assert.equal(candidates.length,2);assert.equal(work.mediaEntries.length,1); });
test("7. 漫畫 +1 話正確保存", () => { const store=storage(),result=V.commitMangaProgress(store,[mangaOnly],[],"manga-1",1,0,"2026-07-16T10:00:00Z");assert.equal(result.media.currentChapter,1);assert.equal(JSON.parse(store.getItem(V.WORKS_KEY))[0].mediaEntries[0].currentChapter,1); });
test("8. 未知總話數可繼續增加", () => { const result=V.updateMangaProgress([mangaOnly],"manga-1",100);assert.equal(result.media.currentChapter,100); });
test("9. 已知總話數不可超過", () => { const work=V.createStandaloneWork("manga",{id:"limited",title:"有限",currentChapter:9,totalChapters:10});const result=V.updateMangaProgress([work],"limited",5);assert.equal(result.media.currentChapter,10); });
test("10. 閱讀歷史正確記錄", () => { const result=V.updateMangaProgress([mangaOnly],"manga-1",5,1,"2026-07-16T10:00:00Z");assert.deepEqual([result.historyRecord.workId,result.historyRecord.mediaId,result.historyRecord.deltaChapters,result.historyRecord.deltaVolumes,result.historyRecord.timestamp],[mangaOnly.workId,"manga-1",5,1,"2026-07-16T10:00:00.000Z"]); });
test("11. 漫畫更新提醒可辨識今天與未閱讀", () => { const info=V.mangaUpdateInfo({...mangaOnly.mediaEntries[0],nextChapterAt:"2026-07-16T08:00:00Z",lastReadAt:"2026-07-15T08:00:00Z"},new Date("2026-07-16T12:00:00Z"));assert.equal(info.today,true);assert.equal(info.unread,true); });
test("12. 無可靠時間時不亂推算", () => { const info=V.mangaUpdateInfo(mangaOnly.mediaEntries[0]);assert.equal(info.known,false);assert.equal(info.label,"更新時間未知，需人工設定");assert.equal(info.nextChapterAt,undefined); });
test("13. 動畫改編進度未知時不估算", () => { const result=V.adaptationProgress({...mangaOnly.mediaEntries[0],currentChapter:150});assert.equal(result.confirmed,false);assert.equal(result.message,"改編進度尚未確認");assert.equal(result.remainingChapters,null); });
test("14. 漫畫活動仍使用嚴格完整名稱配對", () => { const manga={id:"m1",workId:"w1",mediaType:"manga",title:"藍色漫畫",aliases:["Blue Manga"]};const bad=V.matchEventToAnime({title:"作者簽名會",summary:"藍色漫畫新刊"},manga);const good=V.matchEventToAnime({title:"《藍色漫畫》作者簽名會",publisherSource:true},manga);assert.equal(bad.matched,false);assert.equal(good.matched,true);assert.ok(good.score>=80); });
test("15. 電子書網址只接受 http／https", () => { const links=V.normalizeEbookLinks([{platform:"Kobo",url:"https://example.com/book"},{platform:"Kindle",url:"javascript:alert(1)"},{platform:"其他",url:"file:///tmp/book"}]);assert.equal(links.length,1);assert.equal(links[0].platform,"Kobo"); });
test("16. 搜尋可找到只有漫畫的作品、作者與出版社", () => { assert.equal(V.searchWorks([mangaOnly],"只有漫畫").length,1);assert.equal(V.searchWorks([mangaOnly],"作者甲").length,1);assert.equal(V.searchWorks([mangaOnly],"出版社甲").length,1); });
test("17. 備份匯入保留漫畫、平台與閱讀歷史", () => { const work=V.normalizeWork({...mangaOnly,mediaEntries:[{...mangaOnly.mediaEntries[0],ebookLinks:[{platform:"Readmoo",url:"https://example.com/readmoo",manuallyAdded:true}]}]});const history=[{id:"r1",workId:work.workId,mediaId:"manga-1",deltaChapters:1,deltaVolumes:0,timestamp:"2026-07-16T10:00:00Z"}];const backup=V.createBackup({animeList:[],works:[work],mangaReadHistory:history});const result=V.importBackup({animeList:[],works:[],mangaReadHistory:[]},backup,"replace");assert.equal(result.works[0].mediaEntries[0].ebookLinks[0].platform,"Readmoo");assert.equal(result.mangaReadHistory.length,1); });
test("18. Supabase 依 workId／mediaId／updatedAt 保留較新漫畫資料", () => { const local=V.normalizeWork({...mangaOnly,workId:"w-sync",mediaEntries:[{...mangaOnly.mediaEntries[0],id:"m-sync",currentChapter:10,updatedAt:"2026-07-01"}]});const cloud=V.normalizeWork({...mangaOnly,workId:"w-sync",mediaEntries:[{...mangaOnly.mediaEntries[0],id:"m-sync",currentChapter:20,updatedAt:"2026-07-15"}]});const result=V.mergeCloudPayload({animeList:[],works:[local],mangaReadHistory:[]},{animeList:[],works:[cloud],mangaReadHistory:[]});assert.equal(result.works[0].mediaEntries[0].currentChapter,20); });
test("19. 舊動畫功能入口與主 key 保持不變", () => { const html=fs.readFileSync(path.resolve(__dirname,"..","index.html"),"utf8");assert.match(html,/const STORAGE_KEY = "anime_list_v8_8"/);assert.match(html,/data-progress-action="increment"/);assert.match(html,/🎵 主題曲/);assert.match(html,/🎪 查活動/); });
test("20. 跨媒體程式不寫入 events.json", () => { const source=fs.readFileSync(path.resolve(__dirname,"..","cross-media.js"),"utf8");assert.doesNotMatch(source,/writeFile|events\.json\s*=|fetch\([^)]*events\.json[^)]*,\s*\{\s*method\s*:\s*["'](?:POST|PUT|DELETE)/i); });
test("21. 跨媒體程式不修改 GitHub Actions", () => { const source=fs.readFileSync(path.resolve(__dirname,"..","cross-media.js"),"utf8");assert.doesNotMatch(source,/\.github\/workflows|workflow_dispatch|gh\s+/i); });
test("22. 閱讀統計只來自歷史而非 currentChapter", () => { const stats=V.mangaStats([], [V.createStandaloneWork("manga",{title:"舊進度",currentChapter:72})], new Date("2026-07-16T12:00:00Z"));assert.deepEqual([stats.today,stats.week,stats.month,stats.total],[0,0,0,0]); });
test("23. 動畫改編差距只使用人工確認資料", () => { const result=V.adaptationProgress({...mangaOnly.mediaEntries[0],currentChapter:150,animeAdaptedToChapter:65});assert.equal(result.confirmed,true);assert.equal(result.remainingChapters,85); });
test("24. 人工漫畫關聯不被較新自動資料覆蓋", () => { const local=V.normalizeWork({workId:"locked",title:"作品",mediaEntries:[{id:"m",mediaType:"manga",title:"人工選擇",sourceId:"1",relationLocked:true,updatedAt:"2026-01-01"}]});const remote=V.normalizeWork({workId:"locked",title:"作品",mediaEntries:[{id:"m",mediaType:"manga",title:"自動覆蓋",sourceId:"1",relationLocked:false,updatedAt:"2026-12-01"}]});assert.equal(V.mergeWorks([local],[remote])[0].mediaEntries[0].title,"人工選擇"); });
test("25. 人工 media／work 排除仍優先於活動標題", () => { const manga={id:"m1",workId:"w1",mediaType:"manga",title:"藍色漫畫"};assert.equal(V.matchEventToAnime({title:"藍色漫畫 原畫展"},manga,{excludeMediaIds:["m1"]}).matched,false);assert.equal(V.matchEventToAnime({title:"藍色漫畫 原畫展"},manga,{excludeWorkIds:["w1"]}).matched,false); });

if(!process.exitCode)console.log(`\nManga/cross-media tests passed: ${passed}/25`);
